swagger: '2.0'
info:
  description: API fro shoes shop
  version: '2020-11-08T13:07:03Z'
  title: prod-product-service
  contact:
    name: Kalita Mikhail
    url: 'https://github.com/kalitamih'
    email: mkalita1991@gmail.com
  license:
    name: Licensing
    url: 'https://github.com/kalitamih'
host: z2gow2hl38.execute-api.eu-west-1.amazonaws.com
basePath: /prod
schemes:
  - https
paths:
  '/product/{productId}':
    get:
      tags:
        - Product
      produces:
        - application/json
      parameters:
        - name: productId
          in: path
          required: true
          type: string
          format: uuid
      responses:
        '200':
          description: 200 response
          schema:
            $ref: '#/definitions/ProductResponse'
        '400':
          description: 400 response
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: 404 response
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: 500 response
          schema:
            $ref: '#/definitions/ErrorResponse'
    options:
      parameters:
        - name: productId
          in: path
          required: true
          type: string
          format: uuid
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
  /products:
    get:
      tags:
        - Products
      produces:
        - application/json
      responses:
        '200':
          description: 200 response
          schema:
            $ref: '#/definitions/ProductsResponse'
        '500':
          description: 500 response
          schema:
            $ref: '#/definitions/ErrorResponse'
    post:
      tags:
        - CreateProduct
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: produApiGaKS4H7RZWUK0Q
          required: true
          schema:
            $ref: '#/definitions/produApiGaKS4H7RZWUK0Q'
      responses:
        '204':
          description: 204 response
          schema:
            $ref: '#/definitions/NoContentResponse'
        '400':
          description: 400 response
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: 500 response
          schema:
            $ref: '#/definitions/ErrorResponse'
    options:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
definitions:
  NoContentResponse:
    type: object
    properties:
      message:
        type: string
    description: No content!
  ProductResponse:
    type: object
    properties:
      image:
        type: string
      price:
        type: number
      count:
        type: integer
      description:
        type: string
      id:
        type: string
        format: uuid
      title:
        type: string
    description: This is product
  ProductsResponse:
    type: array
    description: This is product
    items:
      type: object
      properties:
        image:
          type: string
        price:
          type: number
        count:
          type: integer
        description:
          type: string
        id:
          type: string
          format: uuid
        title:
          type: string
  produApiGaKS4H7RZWUK0Q:
    type: object
    required:
      - price
      - title
    properties:
      price:
        type: number
      count:
        type: integer
      description:
        type: string
      title:
        type: string
    title: Product
  ErrorResponse:
    type: object
    properties:
      message:
        type: string
    description: This is an error
